# Generated by Django 4.0.4 on 2022-09-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_time', models.FloatField(default=0)),
                ('motor_run_time', models.FloatField(default=0)),
                ('water_motor_run_time', models.FloatField(default=0)),
                ('is_process_started', models.BooleanField(default=False)),
            ],
        ),
    ]
