# Generated by Django 4.0.4 on 2022-09-13 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardwarecontrols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_images_captured', models.IntegerField(default=0)),
                ('total_healthy_images', models.IntegerField(default=0)),
                ('total_diseased_images', models.IntegerField(default=0)),
                ('is_current_session', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_image_capture', models.BooleanField(default=False)),
                ('hardware_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardwarecontrols.hardwareinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SessionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hardware_images')),
                ('disease_name', models.TextField()),
                ('is_healthy', models.BooleanField(default=True)),
                ('hardware_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwarecontrols.hardwaresession')),
            ],
        ),
    ]
