# Generated by Django 4.0.4 on 2022-09-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwarecontrols', '0003_alter_sessionimage_disease_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaresession',
            name='is_session_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
