# Generated by Django 4.0.4 on 2022-09-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwarecontrols', '0004_hardwaresession_is_session_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
