# Generated by Django 4.0.4 on 2022-09-21 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prediction', '0004_rename_serverity_disease_severity'),
        ('hardwarecontrols', '0005_alter_hardwareinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaresession',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionimage',
            name='disease_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prediction.disease'),
        ),
    ]
