# Generated by Django 4.0.4 on 2022-09-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwarecontrols', '0007_hardwaresession_time_alter_hardwaresession_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwaresession',
            name='time',
        ),
        migrations.AlterField(
            model_name='hardwaresession',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
