# Generated by Django 4.0.4 on 2022-09-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwarecontrols', '0008_remove_hardwaresession_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaresession',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
