# Generated by Django 4.0.4 on 2022-09-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwarecontrols', '0009_alter_hardwaresession_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaresession',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
